version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: weatherapi_postgres
    environment:
      POSTGRES_DB: weatherapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherapi_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/weatherapi?sslmode=disable
    volumes:
      - ./cmd/config/config.yaml:/root/config.yaml:ro
    restart: unless-stopped

volumes:
  postgres_data: